package com.handynest.common.api;

public enum ApiErrorCode {
  ACCESS_DENIED,
  BAD_REQUEST,
  CONFLICT,
  CONSENT_REQUIRED,
  DUPLICATE_RESOURCE,
  FEATURE_DISABLED,
  IDEMPOTENCY_KEY_CONFLICT,
  INTERNAL_ERROR,
  INVALID_STATUS_TRANSITION,
  LEGACY_API_DISABLED,
  NOT_FOUND,
  RATE_LIMITED,
  UNAUTHORIZED,
  VALIDATION_ERROR,
  VERIFICATION_REQUIRED
}
