package com.handynest.identity;

public enum ConsentType {
  TERMS_OF_SERVICE,
  PRIVACY_POLICY,
  PERSONAL_DATA_PROCESSING,
  PERFORMER_RULES,
  CUSTOMER_RULES,
  PROHIBITED_SERVICES_POLICY,
  PAYMENT_POLICY
}
