package com.handynest.notification;

public enum NotificationType {
  USER_REGISTERED,
  TASK_CREATED,
  TASK_PUBLISHED,
  TASK_REJECTED,
  TASK_EXPIRED,
  NEW_OFFER,
  OFFER_ACCEPTED,
  OFFER_REJECTED,
  OFFER_EXPIRED,
  DEAL_CREATED,
  CONTACT_REVEALED,
  DEAL_CANCELED,
  NEW_CHAT_MESSAGE,
  WORK_SUBMITTED,
  WORK_ACCEPTED,
  REVISION_REQUESTED,
  DISPUTE_OPENED,
  DISPUTE_RESOLVED,
  FEEDBACK_CREATED,
  VERIFICATION_APPROVED,
  VERIFICATION_REJECTED,
  USER_BLOCKED,
  PAYMENT_EVENT
}
